### ISSUE TITLE
Server doesn't retrieve work items (code 415)

### ISSUE THREAD

**Issue by a-kokorev** [a-kokorev/aims-project#4]
Error description:
```
Error: Request failed with status code 415
    at createError (C:\Projects\aims-project\server\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Projects\aims-project\server\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Projects\aims-project\server\node_modules\axios\lib\adapters\http.js:236:11)
```

More info: [HTTP code 415](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/415)

Probably since the code was written quite a while ago, ADO API has changed and used media type is no longer used

**Comment by a-kokorev** [comment]
Work Items - Get Work Item ADO API: https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work-items/get-work-item?view=azure-devops-rest-6.0
